version: '3'
services:
  website:
    container_name: capstone-website
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - shared-network

networks:
  shared-network:
    external: true
