-- Multi-doctor patient access (primary + specialist) via join table.
-- Safe to run multiple times due to IF NOT EXISTS guards.

create table if not exists public.doctor_patient_access (
  id bigint generated by default as identity primary key,
  patient_user_key text not null references public.users(user_key) on delete cascade,
  doctor_user_key text not null references public.users(user_key) on delete cascade,
  access_type text not null default 'specialist' check (access_type in ('primary', 'specialist')),
  is_active boolean not null default true,
  granted_by_user_key text null references public.users(user_key),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (patient_user_key, doctor_user_key)
);

create index if not exists idx_dpa_patient_active
  on public.doctor_patient_access (patient_user_key, is_active);

create index if not exists idx_dpa_doctor_active
  on public.doctor_patient_access (doctor_user_key, is_active);

alter table public.doctor_patient_access enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'doctor_patient_access'
      and policyname = 'dpa_select_own_links'
  ) then
    create policy dpa_select_own_links
      on public.doctor_patient_access
      for select
      to authenticated
      using (doctor_user_key = auth.uid()::text or patient_user_key = auth.uid()::text);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'doctor_patient_access'
      and policyname = 'dpa_doctor_insert_own_links'
  ) then
    create policy dpa_doctor_insert_own_links
      on public.doctor_patient_access
      for insert
      to authenticated
      with check (doctor_user_key = auth.uid()::text);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'doctor_patient_access'
      and policyname = 'dpa_doctor_update_own_links'
  ) then
    create policy dpa_doctor_update_own_links
      on public.doctor_patient_access
      for update
      to authenticated
      using (doctor_user_key = auth.uid()::text)
      with check (doctor_user_key = auth.uid()::text);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'doctor_patient_access'
      and policyname = 'dpa_doctor_delete_own_links'
  ) then
    create policy dpa_doctor_delete_own_links
      on public.doctor_patient_access
      for delete
      to authenticated
      using (doctor_user_key = auth.uid()::text);
  end if;
end $$;
