-- Subject-based chat threads between patients and doctors + realtime messages.
-- Designed for schemas where users.user_key is TEXT.

create table if not exists public.chat_threads (
  thread_key text primary key,
  patient_user_key text not null references public.users(user_key) on delete cascade,
  doctor_user_key text not null references public.users(user_key) on delete cascade,
  subject text not null,
  created_by_user_key text null references public.users(user_key),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (patient_user_key, doctor_user_key, subject)
);

create index if not exists idx_chat_threads_patient
  on public.chat_threads (patient_user_key, updated_at desc);

create index if not exists idx_chat_threads_doctor
  on public.chat_threads (doctor_user_key, updated_at desc);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  thread_key text not null references public.chat_threads(thread_key) on delete cascade,
  sender_user_key text not null references public.users(user_key) on delete cascade,
  sender_role text not null check (sender_role in ('patient', 'doctor')),
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_messages_thread_created
  on public.chat_messages (thread_key, created_at asc);

alter table public.chat_threads enable row level security;
alter table public.chat_messages enable row level security;

do $$
begin
  -- THREADS: read if participant
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='chat_threads' and policyname='chat_threads_select_participants'
  ) then
    create policy chat_threads_select_participants
      on public.chat_threads
      for select
      to authenticated
      using (patient_user_key = auth.uid()::text or doctor_user_key = auth.uid()::text);
  end if;

  -- THREADS: insert if participant
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='chat_threads' and policyname='chat_threads_insert_participants'
  ) then
    create policy chat_threads_insert_participants
      on public.chat_threads
      for insert
      to authenticated
      with check (patient_user_key = auth.uid()::text or doctor_user_key = auth.uid()::text);
  end if;

  -- THREADS: update if participant
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='chat_threads' and policyname='chat_threads_update_participants'
  ) then
    create policy chat_threads_update_participants
      on public.chat_threads
      for update
      to authenticated
      using (patient_user_key = auth.uid()::text or doctor_user_key = auth.uid()::text)
      with check (patient_user_key = auth.uid()::text or doctor_user_key = auth.uid()::text);
  end if;

  -- MESSAGES: read if thread participant
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='chat_messages' and policyname='chat_messages_select_participants'
  ) then
    create policy chat_messages_select_participants
      on public.chat_messages
      for select
      to authenticated
      using (
        exists (
          select 1
          from public.chat_threads t
          where t.thread_key = chat_messages.thread_key
            and (t.patient_user_key = auth.uid()::text or t.doctor_user_key = auth.uid()::text)
        )
      );
  end if;

  -- MESSAGES: insert if sender is current user and participant
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='chat_messages' and policyname='chat_messages_insert_sender_participant'
  ) then
    create policy chat_messages_insert_sender_participant
      on public.chat_messages
      for insert
      to authenticated
      with check (
        sender_user_key = auth.uid()::text
        and exists (
          select 1
          from public.chat_threads t
          where t.thread_key = chat_messages.thread_key
            and (t.patient_user_key = auth.uid()::text or t.doctor_user_key = auth.uid()::text)
        )
      );
  end if;
end $$;

